@startuml classes

class App

class Image
{
    +path : str
    +image : np.array
}

class Config
class Chain

interface Operation
{
    + TYPE : str
    +process(Image) -> Image
}

class Rotation
class Tint
class Crop
class Blur
class GaussianBlur
class GammaCorrection
class Resize
class Macro

App --> Image : 1..n
App -> Config

Config --> Chain : 1..n
Config --> Macro : 1..n

Chain --> Operation : 1..n
Macro --> Operation : 1..n

Operation <|.. Rotation
Operation <|.. Tint
Operation <|.. Crop
Operation <|.. Blur
Operation <|.. GaussianBlur
Operation <|.. GammaCorrection
Operation <|.. Resize
Macro ..|> Operation


@enduml