@startuml classes

interface Algorithm
{
    +process(Image) -> Image
}

class Rotation
{
    -degree : float
    +process(Image) -> Image
}

class Tint
{
    -color : Color
    +process(Image) -> Image
}

class Crop
{
    {field}-dimension : Dimension
    +process(Image) -> Image
}

class Image
{
    +name : str
    +path : str
    +image : np.array
}

Algorithm - Image
Algorithm <|.. Rotation
Algorithm <|.. Tint
Algorithm <|.. Crop



@enduml