name: ci
on: [ push ]
jobs:
  check-smart-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check format
        run: black . --check --verbose
      - name: Run Unit Tests
        run: pytest